create extension if not exists pgcrypto;

do $$
begin
  create type public.user_role as enum ('customer', 'master', 'admin');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.order_status as enum (
    'new',
    'assigned',
    'accepted',
    'in_progress',
    'completed',
    'cancelled'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.payment_status as enum ('pending', 'paid', 'refunded');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  phone text,
  role public.user_role not null default 'customer',
  city text,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id integer generated by default as identity primary key,
  name text not null unique,
  description text,
  base_price integer not null check (base_price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.masters (
  id integer generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  description text,
  hourly_rate integer check (hourly_rate is null or hourly_rate >= 0),
  verified boolean not null default false,
  available boolean not null default false,
  rating_avg numeric(3, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  master_id uuid references public.profiles(id) on delete set null,
  service_id integer not null references public.services(id),
  problem_description text not null,
  address text not null,
  city text not null default 'Kosice',
  preferred_datetime timestamptz,
  status public.order_status not null default 'new',
  estimated_price integer,
  final_price integer,
  commission_amount integer,
  stripe_payment_status text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.order_photos (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  photo_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ratings (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  master_id uuid not null references public.profiles(id) on delete cascade,
  stars integer not null check (stars between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  stripe_payment_intent_id text,
  amount integer not null check (amount >= 0),
  commission_amount integer not null check (commission_amount >= 0),
  master_amount integer not null check (master_amount >= 0),
  status public.payment_status not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_customer_id on public.orders(customer_id);
create index if not exists idx_orders_master_id on public.orders(master_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_order_photos_order_id on public.order_photos(order_id);
create index if not exists idx_ratings_master_id on public.ratings(master_id);
create index if not exists idx_payments_order_id on public.payments(order_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role public.user_role;
begin
  requested_role := coalesce(new.raw_user_meta_data->>'role', 'customer')::public.user_role;

  if requested_role = 'admin' then
    requested_role := 'customer';
  end if;

  insert into public.profiles (id, full_name, email, phone, role, city)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.email,
    new.raw_user_meta_data->>'phone',
    requested_role,
    new.raw_user_meta_data->>'city'
  )
  on conflict (id) do nothing;

  if requested_role = 'master' then
    insert into public.masters (profile_id)
    values (new.id)
    on conflict (profile_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.masters enable row level security;
alter table public.orders enable row level security;
alter table public.order_photos enable row level security;
alter table public.ratings enable row level security;
alter table public.payments enable row level security;

drop policy if exists "profiles select own or admin" on public.profiles;
create policy "profiles select own or admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own"
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles update own or admin" on public.profiles;
create policy "profiles update own or admin"
on public.profiles
for update
to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "services active public read" on public.services;
create policy "services active public read"
on public.services
for select
to authenticated, anon
using (active = true or public.is_admin());

drop policy if exists "services admin manage" on public.services;
create policy "services admin manage"
on public.services
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "masters readable" on public.masters;
create policy "masters readable"
on public.masters
for select
to authenticated
using (profile_id = auth.uid() or public.is_admin() or (verified = true and available = true));

drop policy if exists "masters insert own or admin" on public.masters;
create policy "masters insert own or admin"
on public.masters
for insert
to authenticated
with check (profile_id = auth.uid() or public.is_admin());

drop policy if exists "masters update own or admin" on public.masters;
create policy "masters update own or admin"
on public.masters
for update
to authenticated
using (profile_id = auth.uid() or public.is_admin())
with check (profile_id = auth.uid() or public.is_admin());

drop policy if exists "orders participant select" on public.orders;
create policy "orders participant select"
on public.orders
for select
to authenticated
using (customer_id = auth.uid() or master_id = auth.uid() or public.is_admin());

drop policy if exists "orders customer insert" on public.orders;
create policy "orders customer insert"
on public.orders
for insert
to authenticated
with check (customer_id = auth.uid() and status = 'new');

drop policy if exists "orders participant update" on public.orders;
create policy "orders participant update"
on public.orders
for update
to authenticated
using (customer_id = auth.uid() or master_id = auth.uid() or public.is_admin())
with check (customer_id = auth.uid() or master_id = auth.uid() or public.is_admin());

drop policy if exists "order photos participant select" on public.order_photos;
create policy "order photos participant select"
on public.order_photos
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.orders
    where orders.id = order_photos.order_id
      and (orders.customer_id = auth.uid() or orders.master_id = auth.uid())
  )
);

drop policy if exists "order photos customer insert" on public.order_photos;
create policy "order photos customer insert"
on public.order_photos
for insert
to authenticated
with check (
  exists (
    select 1 from public.orders
    where orders.id = order_photos.order_id
      and orders.customer_id = auth.uid()
  )
);

drop policy if exists "ratings participant select" on public.ratings;
create policy "ratings participant select"
on public.ratings
for select
to authenticated
using (customer_id = auth.uid() or master_id = auth.uid() or public.is_admin());

drop policy if exists "ratings customer insert" on public.ratings;
create policy "ratings customer insert"
on public.ratings
for insert
to authenticated
with check (
  customer_id = auth.uid()
  and exists (
    select 1 from public.orders
    where orders.id = ratings.order_id
      and orders.customer_id = auth.uid()
      and orders.status = 'completed'
  )
);

drop policy if exists "payments participant select" on public.payments;
create policy "payments participant select"
on public.payments
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.orders
    where orders.id = payments.order_id
      and (orders.customer_id = auth.uid() or orders.master_id = auth.uid())
  )
);

drop policy if exists "payments admin manage" on public.payments;
create policy "payments admin manage"
on public.payments
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('order-photos', 'order-photos', true)
on conflict (id) do update set public = true;

drop policy if exists "order photos public read" on storage.objects;
create policy "order photos public read"
on storage.objects
for select
to public
using (bucket_id = 'order-photos');

drop policy if exists "order photos owner upload" on storage.objects;
create policy "order photos owner upload"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'order-photos'
  and (storage.foldername(name))[1] = auth.uid()::text
);
